<a href="https://colab.research.google.com/github/Sagu12/all-projects/blob/master/Humming_Bird.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install hummingbird-ml

     |████████████████████████████████| 6.7MB 4.6MB/s 
     |████████████████████████████████| 71kB 8.0MB/s 
     |████████████████████████████████| 7.4MB 43.3MB/s 
  Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [2]:
!pip install pyforest

  Created wheel for pyforest: filename=pyforest-1.0.3-py2.py3-none-any.whl size=13715 sha256=dbd80b96a1d9c0885e15157456282f6e8c4a186c577545b2eaec15d21d50b3c1
  Stored in directory: /root/.cache/pip/wheels/af/0b/39/340a7f15fc8d4ff5ab50847b28789afea04452a9d51b9721b5
Successfully built pyforest


In [0]:
from pyforest import *

In [0]:
from hummingbird.ml import convert

In [0]:
#creating random data for binary classification

In [0]:
num_classes=2

In [7]:
X= np.random.rand(100000,28)

<IPython.core.display.Javascript object>

In [8]:
type(X)

numpy.ndarray

In [9]:
X

array([[0.73640404, 0.6508575 , 0.55189863, ..., 0.86898152, 0.29578694,
        0.71965457],
       [0.04761474, 0.42816991, 0.44298143, ..., 0.9169767 , 0.91179491,
        0.18405108],
       [0.42102687, 0.37207104, 0.33071365, ..., 0.95653317, 0.67908097,
        0.69639265],
       ...,
       [0.32851887, 0.60209548, 0.10740817, ..., 0.30258061, 0.63717   ,
        0.10797682],
       [0.39075644, 0.02886967, 0.96451528, ..., 0.40346122, 0.40625949,
        0.36344171],
       [0.33610984, 0.21356819, 0.68278161, ..., 0.90968173, 0.86578642,
        0.18605786]])

In [10]:
X1= np.array(np.random.rand(100000,28), dtype=np.float32)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [11]:
X1

array([[0.286102  , 0.57785183, 0.8744046 , ..., 0.08237923, 0.61040604,
        0.43396625],
       [0.41706902, 0.10710771, 0.7023253 , ..., 0.4527836 , 0.62175196,
        0.7032875 ],
       [0.13280864, 0.26626888, 0.9889398 , ..., 0.7423484 , 0.4662366 ,
        0.8111353 ],
       ...,
       [0.7506929 , 0.2137884 , 0.30979994, ..., 0.6966127 , 0.63059926,
        0.89014244],
       [0.30920574, 0.53411776, 0.37876686, ..., 0.5300756 , 0.16007482,
        0.583575  ],
       [0.6923818 , 0.28599343, 0.6816512 , ..., 0.19214857, 0.09902407,
        0.45130664]], dtype=float32)

In [12]:
y= np.random.randint(2, size=100000)

<IPython.core.display.Javascript object>

In [13]:
len(y)

100000

In [0]:
from sklearn.ensemble import RandomForestClassifier

In [0]:
model= RandomForestClassifier(n_estimators=20, max_depth=10)

In [16]:
model.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=10, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
#use humming bird to convert the model to pytorch

In [0]:
m= convert(model,"pytorch")

In [19]:
m

PyTorchBackendModel(
  (operator_map): ModuleDict(
    (SklearnRandomForestClassifier): PerfectTreeTraversalDecisionTreeImpl(
      (nodes): ParameterList(
          (0): Parameter containing: [torch.LongTensor of size 40]
          (1): Parameter containing: [torch.LongTensor of size 80]
          (2): Parameter containing: [torch.LongTensor of size 160]
          (3): Parameter containing: [torch.LongTensor of size 320]
          (4): Parameter containing: [torch.LongTensor of size 640]
          (5): Parameter containing: [torch.LongTensor of size 1280]
          (6): Parameter containing: [torch.LongTensor of size 2560]
          (7): Parameter containing: [torch.LongTensor of size 5120]
          (8): Parameter containing: [torch.LongTensor of size 10240]
      )
      (biases): ParameterList(
          (0): Parameter containing: [torch.FloatTensor of size 40]
          (1): Parameter containing: [torch.FloatTensor of size 80]
          (2): Parameter containing: [torch.FloatTenso

In [0]:
#RUN HUMMINGBIRD ON CPU AS BY DFEFAULT IT IS RUN ON CPU

In [28]:
%%timeit -r 3

m.predict(X)


10 loops, best of 3: 22.2 ms per loop


In [22]:
%%time

m.to("cuda")

m.predict(X)



CPU times: user 1.61 s, sys: 674 ms, total: 2.28 s
Wall time: 8.38 s


In [0]:
e=m(X)

In [36]:
e[1]

tensor([[0.4979, 0.5021],
        [0.4992, 0.5008],
        [0.5025, 0.4975],
        ...,
        [0.5090, 0.4910],
        [0.4841, 0.5159],
        [0.5092, 0.4908]], device='cuda:0')

In [39]:
e[0][0:10]

tensor([1, 1, 0, 0, 0, 0, 1, 0, 1, 1], device='cuda:0')